version: '3.8'

services:
  auth_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    tty: true
    networks:
        - auth-service_default
        - gateway-service_default

  nginx:
    image: nginx:latest
    container_name: auth_nginx
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - mysql
        - auth_app
    tty: true
    networks:
        - auth-service_default
        - gateway-service_default

  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    tty: true
    networks:
        - auth-service_default

volumes:
  db-data:

networks:
    auth-service_default:
    gateway-service_default:
        external: true
