version: "3.8"

services:
    app:
        build: .
        container_name: email_app
        volumes:
            - .:/var/www
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        container_name: email_nginx
        ports:
            - "8003:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
        tty: true

    mysql:
        image: mysql:8.0
        container_name: email_mysql
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=email
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - db-data:/var/lib/mysql
        tty: true

volumes:
    db-data:
