version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    tty: true

  nginx:
    image: nginx:latest
    container_name: gateway_nginx
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
